# Devoir maison - Apprentissage supervisé
# Cours enseigné par Fabrice Rossi
## Université Paris-Dauphine
## Executive Master Statistique & Big Data
## Auteur: David Thébault

### Introduction

Ce projet s'inscrit dans le cadre de l'Executive Master Statistique et Big Data de Paris-Dauphine et la validation des connaissances en apprentissage supervisé.

Nous utiliserons les techniques et méthodes enseignées pour:
- dans un premier temps nous allons explorer un jeu de données pour caractériser les départements français métropolitains et leurs compositions sur l'ensemble de la population et sur la population active
- dans un second temps conduire une analyse prédictive et constuire un modèle prédictif du salaire _Pay_ en fonction d'autres variables.

Les jeux de données à disposition décrivent les personnes étudiées, leurs emplois pour les personnes actives, le sport s'ils en pratiquent un. Des données relatifs aux variables catégoriques et à la géographie complètent les premiers jeux de données.

In [17]:
# Chargement des différents jeux de données
# Le nombre de fichiers à charger étant conséquents, nous utiliserons un chargement global selon le répertoire.

import os

# récupérer le chemin du répertoire courant
path = os.getcwd()
print("Le répertoire courant est : " + path)

# récupérer le nom du répertoire courant
repn = os.path.basename(path)
print("Le nom du répertoire est : " + repn)

Le répertoire courant est : /Users/davidtbo/OneDrive/Documents/Data_Science/17_Apprentissage_supervisé
Le nom du répertoire est : 17_Apprentissage_supervisé

In [18]:
# Liste des fichiers de notre répertoire

#list = os.listdir('.')
#print(list)

# Méthode 2: Liste des fichiers du répertoire
FichList = [ f for f in os.listdir('.') if os.path.isfile(os.path.join('.',f)) ]
#print(FichList)

In [19]:
path_data = './project-9/project-9-files'

In [20]:
list = os.listdir(path_data)
print(list)

['.Rhistory', 'code_act.csv', 'Projet_ML_Explanatory_Analysis_DThébault.Rmd', 'regions.csv', 'code_job_42.csv', 'code_JOB_CONDITION.csv', 'city_pop.csv', 'city_adm.csv', 'test.csv', 'departments.csv', 'code_Work_desc_n2.csv', 'Projet_ML_Predictive_Analysis_DThébault.Rmd', 'code_Work_desc_map.csv', 'learn.csv', 'code_Work_desc_n1.csv', 'learn_sports.csv', 'city_loc.csv', 'code_type_of_contract.csv', 'code_highest_degree.csv', 'code_Familty_type.csv', 'test_sports.csv', 'code_Job_category.csv', 'code_Work_desc.csv', 'code_EMPLOYER_CATEGORY.csv', '.RData', 'code_Employee_count.csv', 'learn_job.csv', 'learn_emp_type.csv', 'code_sports.csv', 'code_emp_type.csv', 'code_eco_sect.csv']

In [6]:
FichList = [f for f in list if os.path.isfile(os.path.join('.',f))]
print(FichList)

['.Rhistory', '.RData']

In [9]:
import os
import pandas as pd

code_act.csv
regions.csv
code_job_42.csv
code_JOB_CONDITION.csv
city_pop.csv
city_adm.csv
test.csv
departments.csv
code_Work_desc_n2.csv
code_Work_desc_map.csv
learn.csv
code_Work_desc_n1.csv
learn_sports.csv
city_loc.csv
code_type_of_contract.csv
code_highest_degree.csv
code_Familty_type.csv
test_sports.csv
code_Job_category.csv
code_Work_desc.csv
code_EMPLOYER_CATEGORY.csv
code_Employee_count.csv
learn_job.csv
learn_emp_type.csv
code_sports.csv
code_emp_type.csv
code_eco_sect.csv
['./project-9/project-9-files/code_act.csv', './project-9/project-9-files/regions.csv', './project-9/project-9-files/code_job_42.csv', './project-9/project-9-files/code_JOB_CONDITION.csv', './project-9/project-9-files/city_pop.csv', './project-9/project-9-files/city_adm.csv', './project-9/project-9-files/test.csv', './project-9/project-9-files/departments.csv', './project-9/project-9-files/code_Work_desc_n2.csv', './project-9/project-9-files/code_Work_desc_map.csv', './project-9/project-9-files/learn.csv', './project-9/project-9-files/code_Work_desc_n1.csv', './project-9/project-9-files/learn_sports.csv', './project-9/project-9-files/city_loc.csv', './project-9/project-9-files/code_type_of_contract.csv', './project-9/project-9-files/code_highest_degree.csv', './project-9/project-9-files/code_Familty_type.csv', './project-9/project-9-files/test_sports.csv', './project-9/project-9-files/code_Job_category.csv', './project-9/project-9-files/code_Work_desc.csv', './project-9/project-9-files/code_EMPLOYER_CATEGORY.csv', './project-9/project-9-files/code_Employee_count.csv', './project-9/project-9-files/learn_job.csv', './project-9/project-9-files/learn_emp_type.csv', './project-9/project-9-files/code_sports.csv', './project-9/project-9-files/code_emp_type.csv', './project-9/project-9-files/code_eco_sect.csv']

In [ ]:
liste = [] # initialisation de la liste qui va nous servir à stocker les fichiers
for path, subdirs, files in os.walk(path_data): # objet contenant un path,subdirs et les files
    for name in files: # pour tous les fichiers
        if name[-4:] == '.csv': # si le fichier se termine par .csv
            #print(os.path.join(path, name)) # alors affiche son répertoire/name
            liste = liste + [os.path.join(path, name)]
            print(name)
print(liste)

In [8]:
file_count = len(liste)

# create empty list
dataframes_list = []
  
# append datasets to the list 
for i in range(file_count):
    df = pd.read_csv(liste[i])
    dataframes_list.append(df)
      
# display datsets
#for dataset in dataframes_list:
#    display(dataset)

# len(liste) = 27
dataframes_list[10]

# on pourrait renommer les dataframes avec leur nom d'origine...

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,pkey,First_name,L_NAME,act,age_2020,STUDYING,Familty_type,highest_degree,Insee,job_42,SEX
0,1.0,JEAN,ROBINET,AT_2_1,81,False,ft4-4,dipl-1-8,01004,csp_7_7,Male
1,2.0,CLARISSE,CANIPEL,AT_1_2,29,False,ft4-2,dipl-1-5,01004,csp_6_7,Female
2,3.0,NICOLE,COURTAILLER,AT_1_1,61,False,ft3-2,dipl-1-3,01004,csp_5_5,Female
3,4.0,GUY,MORAND,AT_2_1,63,False,ft4-4,dipl-1-6,01004,csp_7_5,Male
4,5.0,CORENTIN,MAGNE,AT_2_2,17,True,ft4-1,dipl-1-2,01004,csp_8_4,Male
...,...,...,...,...,...,...,...,...,...,...,...
99995,99996.0,CATHERINE,MOZZI,AT_1_1,53,False,ft4-1,dipl-1-6,95680,csp_4_6,Female
99996,99997.0,DIDIER,MILLIOT,AT_1_1,57,False,ft4-1,dipl-1-6,95680,csp_3_7,Male
99997,99998.0,NADIA,GERBON,AT_1_1,46,False,ft4-1,dipl-1-5,95680,csp_5_2,Female
99998,99999.0,SYLVIE,ARMANETTI,AT_1_1,61,False,ft4-1,dipl-1-3,95680,csp_6_8,Female
99999,100000.0,SERGE,TURPAUD,AT_2_1,85,False,ft1-1,dipl-2,95680,csp_7_2,Male

In [60]:
range(len(liste))

range(0, 27)

In [54]:
d = concat([read_csv(f, index_col=0, header=None, axis=1) for f in files], keys=files)

0
./project-9/project-9-files/code_act.csv

ValueError: Wrong number of items passed 2, placement implies 1

In [36]:
df

   Code                                            Libellé
0    AZ                 Agriculture, sylviculture et pêche
1    BZ                             Industries extractives
2    CA  Fabrication de denrées alimentaires, de boisso...
3    CB  Fabrication de textiles, industries de l'habil...
4    CC  Travail du bois, industries du papier et impri...
5    CD                           Cokéfaction et raffinage
6    CE                                 Industrie chimique
7    CF                           Industrie pharmaceutique
8    CG  Fabrication de produits en caoutchouc et en pl...
9    CH  Métallurgie et fabrication de produits métalli...
10   CI  Fabrication de produits informatiques, électro...
11   CJ              Fabrication d'équipements électriques
12   CK      Fabrication de machines et équipements n.c.a.
13   CL              Fabrication de matériels de transport
14   CM  Autres industries manufacturières ; réparation...
15   DZ  Production et distribution d'électricité, de g...
16   EZ  Production et distribution d'eau ; assainissem...
17   FZ                                       Construction
18   GZ  Commerce ; réparation d'automobiles et de moto...
19   HZ                          Transports et entreposage
20   IZ                        Hébergement et restauration
21   JA                  Edition, audiovisuel et diffusion
22   JB                                 Télécommunications
23   JC  Activités informatiques et services d'information
24   KZ               Activités financières et d'assurance
25   LZ                             Activités immobilières
26   MA  Activités juridiques, comptables, de gestion, ...
27   MB               Recherche-développement scientifique
28   MC  Autres activités spécialisées, scientifiques e...
29   NZ  Activités de services administratifs et de sou...
30   OZ                            Administration publique
31   PZ                                       Enseignement
32   QA                    Activités pour la santé humaine
33   QB  Hébergement médico-social et social et action ...
34   RZ          Arts, spectacles et activités récréatives
35   SZ                       Autres activités de services
36   TZ  Activités des ménages en tant qu'employeurs ; ...
37   UZ                      Activités extra-territoriales